### ISSUE TITLE
Unable to fetch user attributes post authentication 

### ISSUE THREAD

**Issue by vijam** [lucianw/ldap-jwt#10]
,I'm not sure something which is still can support here ?I have cloned this project and using in my work , with this authentication is success and token is getting generated, but user attributes I'm not able to get .

**Comment by lucianweber** [comment]
This does not sound like a problem with this project but with JWT in general. Maybe jwt.io can help you understand the concept more clearly. Otherwise, if you still have questions about the concept, you should go to Stack Overflow and specify your question more clearly there.
GitHub Issues for this project are definitely the wrong place for it.
