### ISSUE TITLE
API for managing ldap users and passwords 

### ISSUE THREAD

**Issue by lucallero** [lucianw/ldap-jwt#2]
An API for create ldap users and manage their passwords would be a nice feature. About the endpoints approach I was wondering if we go RESTFull API, what would be something like...
```
/users
/users{user-name}
/users{user-name}/password
```
or RPC like, using operations similar as `/authenticate`, like
```
/add
/passwd
```
I'm actually working on it,  any thoughts are welcome.

**Comment by lucianweber** [comment]
Hey, thanks for the input!

To be honest, I am not shure if this project should provide these endpoints, since it would be pretty hard to generalize them, but I would like to hear your proposal on this.

Anonther reason agains adding these endpoints is the growing size of the code. Since this is a project that tries to secure webapps with tokens, most of the users will at least scan the code for obvious mistakes before using it in their project. So if we add a lot of code they might not be willing to do that anymore and therefore won't use it in their project. On the other hand we would need to add configuration for this feature to make it optional, since not everybody will want to activate it.
I hope you understand my hesitation. If you see it differently, please let me know!

**Comment by lucallero** [comment]
Agree with you, after implementing it I had to import the code to a private gitlab, in order no to pollute with internal needs. 
I'll see what I can do to keep it clean and useful. If I managed to do it I'll let you know.
Thanks for your attention.
